[project]
name = "escrow_contract"
version = "0.1.0"
authors = ["0xReady"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = "0.15"
fuels-abigen-macro = "0.15"
rand = "0.5"
tokio = { version = "1.12", features = ["rt", "macros"] }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
