/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  ContractCall,
  ContractCallOptions,
  Overrides,
  BigNumberish,
  BytesLike,
  CallResult,
  ScriptTransactionRequest,
  TransactionResult,
} from "fuels";

export type AddressInput = { value: string };

export type Address = { value: string };

export type ContractIdInput = { value: string };

export type ContractId = { value: string };

interface EscrowContractAbiInterface extends Interface {
  functions: {
    create: FunctionFragment;
    accept: FunctionFragment;
    revert: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "create",
    values: [AddressInput, ContractIdInput, BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "accept",
    values: [BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "revert",
    values: [BigNumberish]
  ): Uint8Array;

  decodeFunctionData(functionFragment: "create", data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: "accept", data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: "revert", data: BytesLike): DecodedValue;
}

export class EscrowContractAbi extends Contract {
  interface: EscrowContractAbiInterface;
  prepareCall: {
    create(
      receiver: AddressInput,
      requested_asset_id: ContractIdInput,
      requested_asset_amount: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    accept(
      escrow_id: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    revert(
      escrow_id: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;
  };
  submit: {
    create(
      receiver: AddressInput,
      requested_asset_id: ContractIdInput,
      requested_asset_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<bigint>;

    accept(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    revert(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;
  };
  submitResult: {
    create(
      receiver: AddressInput,
      requested_asset_id: ContractIdInput,
      requested_asset_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    accept(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    revert(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;
  };
  dryRun: {
    create(
      receiver: AddressInput,
      requested_asset_id: ContractIdInput,
      requested_asset_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<bigint>;

    accept(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    revert(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;
  };
  dryRunResult: {
    create(
      receiver: AddressInput,
      requested_asset_id: ContractIdInput,
      requested_asset_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    accept(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    revert(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;
  };
  simulate: {
    create(
      receiver: AddressInput,
      requested_asset_id: ContractIdInput,
      requested_asset_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<bigint>;

    accept(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    revert(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;
  };
  simulateResult: {
    create(
      receiver: AddressInput,
      requested_asset_id: ContractIdInput,
      requested_asset_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    accept(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    revert(
      escrow_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;
  };

  create(
    receiver: AddressInput,
    requested_asset_id: ContractIdInput,
    requested_asset_amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<bigint>;

  accept(
    escrow_id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  revert(
    escrow_id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;
}
